// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace OSMRoad
{
    public partial class OsmroadContext : DbContext
    {
        public OsmroadContext()
        {
        }

        public OsmroadContext(DbContextOptions<OsmroadContext> options)
            : base(options)
        {
        }

        public virtual DbSet<RoadsTehran> RoadsTehran { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<RoadsTehran>(entity =>
            {
                entity.HasKey(e => e.Objectid)
                    .HasName("PK__ROADS_TE__F4B70D85D8590C35");

                entity.ToTable("ROADS_TEHRAN");

                entity.Property(e => e.Objectid).HasColumnName("OBJECTID");

                entity.Property(e => e.Bridge)
                    .HasColumnName("bridge")
                    .HasMaxLength(1);

                entity.Property(e => e.Code).HasColumnName("code");

                entity.Property(e => e.Fclass)
                    .HasColumnName("fclass")
                    .HasMaxLength(28);

                entity.Property(e => e.FidRoads).HasColumnName("FID_ROADS");

                entity.Property(e => e.Layer)
                    .HasColumnName("layer")
                    .HasColumnType("numeric(12, 0)");

                entity.Property(e => e.Maxspeed).HasColumnName("maxspeed");

                entity.Property(e => e.Name)
                    .HasColumnName("name")
                    .HasMaxLength(100);

                entity.Property(e => e.Oneway)
                    .HasColumnName("oneway")
                    .HasMaxLength(1);

                entity.Property(e => e.OsmId)
                    .HasColumnName("osm_id")
                    .HasMaxLength(10);

                entity.Property(e => e.Ref)
                    .HasColumnName("ref")
                    .HasMaxLength(20);

                entity.Property(e => e.RegionCode).HasMaxLength(50);

                entity.Property(e => e.RegionName).HasMaxLength(100);

                entity.Property(e => e.Tunnel)
                    .HasColumnName("tunnel")
                    .HasMaxLength(1);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}