// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace OSMRoad
{
    public partial class RoadsTehran
    {
        public int Objectid { get; set; }
        public int? FidRoads { get; set; }
        public string OsmId { get; set; }
        public short? Code { get; set; }
        public string Fclass { get; set; }
        public string Name { get; set; }
        public string Ref { get; set; }
        public string Oneway { get; set; }
        public short? Maxspeed { get; set; }
        public decimal? Layer { get; set; }
        public string Bridge { get; set; }
        public string Tunnel { get; set; }
        public string RegionCode { get; set; }
        public string RegionName { get; set; }
    }
}